Repository AY2425S1-CS2103T-F11-1/tp, pull requests merged in 2024-11, with the labels that each got.

#135 133 fix user guide typos
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation, alpha-bug

#136 134 update help page link
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation, alpha-bug

#142 Edit User Guide Typo errors and formatting
  docs/UserGuide.md
Labels: documentation, alpha-bug

#147 Add notice on index range
  docs/UserGuide.md
Labels: documentation, alpha-bug

#132 131 include concerts and concertcontacts in sampledatautil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: alpha-bug

#144 Add date format to help command usage message
  src/main/java/seedu/address/logic/commands/AddConcertCommand.java
Labels: alpha-bug

#151 143 fix truncation of fields in cards
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/FindConcertCommand.java
  src/main/java/seedu/address/logic/commands/FindConcertContactCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListConcertCommand.java
  src/main/java/seedu/address/logic/commands/ListConcertContactCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/ui/ConcertCard.java
  src/main/java/seedu/address/ui/ConcertContactCard.java
  src/main/java/seedu/address/ui/ConcertContactListPanel.java
  src/main/java/seedu/address/ui/ConcertListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/ConcertContactListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: alpha-bug

#148 Update person duplicate handling
  src/main/java/seedu/address/model/commons/Name.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/commons/NameTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: severity.Medium, alpha-bug

#160 Change command usage message for editc
  src/main/java/seedu/address/logic/commands/EditConcertCommand.java
Labels: alpha-bug

#155 Add extra character input for name argument
  docs/UserGuide.md
  src/main/java/seedu/address/model/commons/Name.java
  src/test/java/seedu/address/model/commons/NameTest.java
Labels: priority.High, severity.Medium, alpha-bug

#156 Change cc view toggle key
  docs/UserGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
Labels: alpha-bug

#165 Update UG
  docs/UserGuide.md
Labels: documentation, alpha-bug

#162 Add more roles for users to choose
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Role.java
Labels: priority.High, severity.Medium, alpha-bug

#167 Update documentation
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: alpha-bug

#248 Update UI ped
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddConcertContactCommand.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#255 Finalise UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/ConcertContactListPanel.java
  src/main/java/seedu/address/ui/ConcertListPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/FindConcertCommandTest.java
  src/test/java/seedu/address/logic/parser/FindConcertCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: documentation
