Repository AY2425S1-CS2103T-F11-1/tp, pull requests merged in 2024-10, with the labels that each got.

#17 Add use cases
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#38 Remove traces of AB3
  README.md
Labels: priority.High

#48 Extract Name and Address to commons
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/commons/Address.java
  src/main/java/seedu/address/model/commons/Name.java
  src/main/java/seedu/address/model/commons/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/commons/AddressTest.java
  src/test/java/seedu/address/model/commons/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/commons/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#95 Fix to DeleteConcertContactCommand
  src/main/java/seedu/address/logic/commands/DeleteConcertContactCommand.java
Labels: type.Bug

#118 112 modify the format for cc commands
  src/main/java/seedu/address/logic/commands/AddConcertContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteConcertContactCommand.java
  src/main/java/seedu/address/logic/parser/AddConcertContactCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteConcertContactCommandParser.java
  src/test/java/seedu/address/logic/parser/AddConcertContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteConcertContactCommandParserTest.java
Labels: type.Task, priority.High
